#!/bin/bash
num1=$((1 + $RANDOM % 100000))
num2=$((1 + $RANDOM % 100000))
sqrt1=$(echo " sqrt($num1)")
sqrt2=$(echo " sqrt($num2)")
echo "The first random number generated is $num1"
echo "The second random number generated is $num2"
echo "The first square root is $sqrt1"
echo "The second square root is $sqrt2"
sum=$(($sqrt1 + $sqrt2))
echo "The sum of their square roots is $sum"
